name: Prebuild Binaries

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [22.x]
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Build native bindings
        run: npx prebuildify --napi --strip --verbose || exit 1

      - name: List prebuild output
        run: ls -R prebuilds

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: prebuild-${{ matrix.os }}
          path: prebuilds/**
